@hostname = http://localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

### Requisição POST 
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "denisio@teste.com",
    "senha": "senhaSegura123!"
}

### Requisição GET de Teste 
GET {{host}}/test
Content-Type: application/json
